---
name: lab-03
break: true
indent: 4
---

src/main/java/labfour:
    HatPurchase.java:
        ConfirmFileExists
        CountSingleLineComments --language Java --count 8
        MatchFileFragment --fragment "TODO" --count 0 --exact
        MatchFileFragment --fragment "double " --count 7
        MatchFileFragment --fragment "boolean " --count 1 --exact
        MatchFileFragment --fragment ">=" --count 1 --exact
        MatchFileFragment --fragment "{YOUR NAME HERE}" --count 0 --exact
        MatchFileRegex --regex "System\.out\.(print|println)" --count 10

writing:
    reflection.md:
        ConfirmFileExists
        mdl --rules ~MD009,~MD012,~MD014,~MD013,~MD022,~MD026
        CountFileWords --count 300
        CountFileParagraphs --count 5
        MatchFileFragment --fragment "TODO" --count 0 --exact
        CountMarkdownTags --tag "code_block" --count 1 --exact
        MatchFileFragment --fragment "{YOUR NAME HERE}" --count 0 --exact
        
CountCommits --count 3
ExecuteCommand --command "gradle build"
CountCommandOutput --command "gradle -q --console plain run" --count 9 --exact
MatchCommandFragment --command "gradle -q --console plain run" --fragment "-120.33" --count 1 --exact
MatchCommandFragment --command "gradle -q --console plain run" --fragment "-54.5" --count 1 --exact
MatchCommandFragment --command "gradle -q --console plain run" --fragment "-5.45" --count 1 --exact
MatchCommandFragment --command "gradle -q --console plain run" --fragment "-232.0" --count 1 --exact
MatchCommandFragment --command "gradle -q --console plain run" --fragment "-693.54" --count 1 --exact
MatchCommandFragment --command "gradle -q --console plain run" --fragment "-234.35" --count 1 --exact
MatchCommandFragment --command "gradle -q --console plain run" --fragment "false" --count 1 --exact
